Feature/10 opentelemetry support
Byndyusoft/Byndyusoft.Logging pull request #12
Opened 2022-07-11 08:42 UTC by Mblkolo

Поддержка OpenTelemetry и OpenTracing в отдельных пакетах

2022-07-13 05:36 UTC, kanybekov requested changes

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTracing/Configuration/LoggerConfigurationExtensions.cs
> +        public static LoggerConfiguration UseOpenTracingTraces(
Меня чуть нейминг смущает, в первом методе — "используй трассы опентрейсинга", а во втором — "пиши в опентрейсинг", хочется, что слово "трассы" использовалось либо везде, либо нигде

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTracing/Configuration/LoggerConfigurationExtensions.cs
> +        /// Добавлять TraceId, SpanId трассы в логи
Клинап кода в этом солюшене не отбивает табы в автодокументации?

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTelemetry/Enrichers/OpenTracingTraceEnricher.cs
> +            {
скобки нужны?

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTelemetry/Enrichers/OpenTracingTraceEnricher.cs
> +            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("TraceId", currentActivity.TraceId));
пустую строку бы добавить после ретурна

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTelemetry/Sinks/OpenTracingSink.cs
> +            {
скобки?

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTelemetry/Sinks/OpenTracingSink.cs
> +                var propertyNames = logEvent.MessageTemplate.Tokens.OfType<PropertyToken>().Select(x => x.PropertyName)
по переносу ToArray(): я бы OfType() и Select() тогда тоже перенос на новые строки

2022-07-13 05:36 UTC, kanybekov commented on src/Byndyusoft.Logging/Byndyusoft.Logging.csproj
> +	<ItemGroup>
отступ

2022-07-14 05:39 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTracing/Configuration/LoggerConfigurationExtensions.cs
> +        public static LoggerConfiguration UseOpenTracingTraces(
В логер падают ид трассы из asp, соответственно метод говорит, что трассы в логах нужно именно использовать трассы опентрейсинга, а не стандартные

2022-07-14 05:41 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTracing/Configuration/LoggerConfigurationExtensions.cs
> +        /// Добавлять TraceId, SpanId трассы в логи
нет, но я сделал клинап на солюшен

2022-07-14 05:42 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Enrichers/OpenTracingTraceEnricher.cs
> +            {
считаю вкусовщиной, но удалил

2022-07-14 05:42 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Enrichers/OpenTracingTraceEnricher.cs
> +            logEvent.AddOrUpdateProperty(propertyFactory.CreateProperty("TraceId", currentActivity.TraceId));
клинап сделал это

2022-07-14 05:42 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Sinks/OpenTracingSink.cs
> +            {
++

2022-07-14 05:43 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Sinks/OpenTracingSink.cs
> +                var propertyNames = logEvent.MessageTemplate.Tokens.OfType<PropertyToken>().Select(x => x.PropertyName)
++

2022-07-14 05:43 UTC, Mblkolo commented on src/Byndyusoft.Logging/Byndyusoft.Logging.csproj
> +	<ItemGroup>
++

2022-07-14 05:44 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Sinks/OpenTracingSink.cs
> +    public class OpenTelemetrySink : ILogEventSink
++

2022-07-14 05:45 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Enrichers/LoggerEnrichmentConfigurationExtensions.cs
> +        [ExcludeFromCodeCoverage]
Удалил все, т.к. атрибуты приехали из предыдущей реализации и от них больше вопросов, чем пользы

2022-07-14 07:31 UTC, kanybekov commented on src/Byndyusoft.Logging.OpenTracing/Configuration/LoggerConfigurationExtensions.cs
> +        public static LoggerConfiguration UseOpenTracingTraces(
ok

2022-07-14 07:33 UTC, kanybekov approved these changes

2022-08-03 04:27 UTC, merged