New Telemetry Usage
Byndyusoft/Byndyusoft.Logging pull request #15
Opened 2024-01-30 06:28 UTC by Rinatich

- Removed duplicated configuration
- Add structured event logging for OpenTelemetry

2024-02-13 05:26 UTC, Mblkolo requested changes

2024-02-13 05:26 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry/Builders/StructuredActivityEventBuilder.cs
> +            fields.Remove(LogEventPropertyNames.StructureActivityEventName);
Лишний Remove

2024-02-13 05:26 UTC, Mblkolo commented on src/Byndyusoft.Logging.OpenTelemetry.Abstractions/Extensions/LoggerExtensions.cs
> +        public static void LogStructuredActivityEvent(
Давай добавим уровень логирования

2024-02-13 05:26 UTC, Mblkolo commented on README.md
> +    new StructuredActivityEventItem("Id", 10, "Id"),
Давай сделаем 2 поля, а не 3

2024-02-13 05:26 UTC, Mblkolo commented on README.md
> +Пример логирования структурных событий:
Чтобы получить в трассах имя события без параметров и управлять названием параметров, нужно логировать по конвенции (пугаем конвенцией) или использовать вспомогательный метод.

Должен параметр TraceEventName

2024-02-13 05:26 UTC, Mblkolo commented on README.md
> +.UseSerilog((context, configuration) => configuration
Вынести в доке выше, а то выглядит так, что это лежит  Byndyusoft.Logging.OpenTelemetry.Abstractions

2024-02-19 08:10 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTelemetry.Abstractions/StructuredActivityEventItem.cs
> +    public class StructuredActivityEventItem
++

2024-02-19 08:11 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTelemetry/Builders/Interfaces/IActivityEventBuilder.cs
> +        /// Строение события активности на основе строки лога
++

2024-02-19 08:13 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTelemetry/Builders/StructuredActivityEventBuilder.cs
> +            fields.Remove(LogEventPropertyNames.StructureActivityEventName);
++

2024-02-19 08:16 UTC, Rinatich commented on README.md
> +    new StructuredActivityEventItem("Id", 10, "Id"),
++

2024-02-19 08:22 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTelemetry.Abstractions/Extensions/LoggerExtensions.cs
> +        public static void LogStructuredActivityEvent(
++

2024-02-19 09:48 UTC, Rinatich commented on README.md
> +Пример логирования структурных событий:
++ Поменял свойство, так лучше

2024-02-19 09:48 UTC, Rinatich commented on README.md
> +.UseSerilog((context, configuration) => configuration
++

2024-02-20 05:02 UTC, Rinatich commented on README.md
> +## Хочу положить в события трассировок только определенные свойства (структурные события)
++

2024-02-20 05:19 UTC, Mblkolo commented on README.md
> +## Хочу положить в события трассировок только определенные свойства (структурные события)
Заголовок по прежнему непонятный

2024-02-20 05:57 UTC, Mblkolo approved these changes

2024-02-21 05:08 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTelemetry/Byndyusoft.Logging.OpenTelemetry.csproj
> +    <ProjectReference Include="..\Byndyusoft.Logging\Byndyusoft.Logging.csproj" />
++

2024-02-21 05:08 UTC, Rinatich commented on src/Byndyusoft.Logging.OpenTracing/Byndyusoft.Logging.OpenTracing.csproj
> +    <ProjectReference Include="..\Byndyusoft.Logging\Byndyusoft.Logging.csproj" />
++

2024-02-21 05:52 UTC, litichevskiydv approved these changes

2024-05-08 07:04 UTC, merged